### ISSUE TITLE
Slow rendering (???)

### ISSUE THREAD

**Issue by hoverek-yt** [demkom58/begin#2] opened 2023-03-16 12:37 UTC
After launching the client and loading the world, I get about 200- 300 FPS, but the game actually stutters a lot. I recorded the game using OBS, and surprisingly the game looks smooth, but the window itself actually "skips frames".

**Comment by demkom58** [comment] 2023-03-16 20:15
This is a weird bug and I don't know how to fix it, or rather I don't have the time or energy to fix it. I'm sorry.

But in general, I noticed that the problem is reflected in the values ​​of the timer that is needed for the game loop.

**Comment by demkom58** [comment] 2023-03-17 17:50
I re-read it and it seems you are describing a different bug that I originally thought of. The bug you describe is very similar to the current state of the game in the `re-registry` branch, are you sure that you now have code from the `master` branch and the last commit matches the current one?

**Comment by demkom58** [comment] 2023-03-25 20:02
Okay, I suddenly found the time and fixed all the bugs that I knew about. If you want, try the latest commit from the master branch.

I am closing this issue.

**Closed by demkom58** 2023-03-25 20:02 UTC
Labels: bug
